module.exports = {
  activities: require("./activities"),
  capitalize: require("./capitalize"),
  colors: require("./colors").colors,
  convert: require("./colorConversions").convert,
  deployLog: require("./deployLog"),
  emojis: require("./emojis"),
  nordChalk: require("./colors").nordChalk,
  permissions: require("./permissions"),
  permissionCheck: require("./permissionCheck"),
  random: require("./random"),
  rep: require("./rep"),
  superEscape: require("./superEscape"),
  timestampStyler: require("./timestampStyler"),
  RGB: require("./colorConversions").RGB,
  HSV: require("./colorConversions").HSV,
  CMYK: require("./colorConversions").CMYK,
}