// Source: https://github.com/M-Media-Group/country-json/blob/master/src/countries-master.json
export default [
  {
    country: "Afghanistan",
    population: "35530081",
    sq_km_area: 652090,
    life_expectancy: "45.9",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "AF",
    location: "Southern and Central Asia",
    iso: "4",
    capital_city: "Kabul"
  },
  {
    country: "Albania",
    population: "2930187",
    sq_km_area: 28748,
    life_expectancy: "71.6",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "AL",
    location: "Southern Europe",
    iso: "8",
    capital_city: "Tirana"
  },
  {
    country: "Algeria",
    population: "41318142",
    sq_km_area: 2381741,
    life_expectancy: "69.7",
    elevation_in_meters: "800",
    continent: "Africa",
    abbreviation: "DZ",
    location: "Northern Africa",
    iso: "12",
    capital_city: "Alger"
  },
  {
    country: "American Samoa",
    population: "55641",
    sq_km_area: 199,
    life_expectancy: "75.1",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "AS",
    location: "Polynesia",
    iso: "16",
    capital_city: "Fagatogo"
  },
  {
    country: "Andorra",
    population: "76965",
    sq_km_area: 468,
    life_expectancy: "83.5",
    elevation_in_meters: "1,996",
    continent: "Europe",
    abbreviation: "AD",
    location: "Southern Europe",
    iso: "20",
    capital_city: "Andorra la Vella"
  },
  {
    country: "Angola",
    population: "29784193",
    sq_km_area: 1246700,
    life_expectancy: "38.3",
    elevation_in_meters: "1,112",
    continent: "Africa",
    abbreviation: "AO",
    location: "Central Africa",
    iso: "24",
    capital_city: "Luanda"
  },
  {
    country: "Anguilla",
    population: "14909",
    sq_km_area: 96,
    life_expectancy: "76.1",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "AI",
    location: "Caribbean",
    iso: "660",
    capital_city: "The Valley"
  },
  {
    country: "Antarctica",
    population: null,
    sq_km_area: 13120000,
    life_expectancy: null,
    elevation_in_meters: "2,300",
    continent: "Antarctica",
    abbreviation: "AQ",
    location: "Antarctica",
    iso: "10",
    capital_city: null
  },
  {
    country: "Antigua and Barbuda",
    population: "102012",
    sq_km_area: 442,
    life_expectancy: "70.5",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "AG",
    location: "Caribbean",
    iso: "28",
    capital_city: "Saint John's"
  },
  {
    country: "Argentina",
    population: "44271041",
    sq_km_area: 2780400,
    life_expectancy: "75.1",
    elevation_in_meters: "595",
    continent: "South America",
    abbreviation: "AR",
    location: "South America",
    iso: "32",
    capital_city: "Buenos Aires"
  },
  {
    country: "Armenia",
    population: "2930450",
    sq_km_area: 29800,
    life_expectancy: "66.4",
    elevation_in_meters: "1,792",
    continent: "Asia",
    abbreviation: "AM",
    location: "Middle East",
    iso: "51",
    capital_city: "Yerevan"
  },
  {
    country: "Aruba",
    population: "105264",
    sq_km_area: 193,
    life_expectancy: "78.4",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "AW",
    location: "Caribbean",
    iso: "533",
    capital_city: "Oranjestad"
  },
  {
    country: "Australia",
    population: "24450561",
    sq_km_area: 7741220,
    life_expectancy: "79.8",
    elevation_in_meters: "330",
    continent: "Oceania",
    abbreviation: "AU",
    location: "Australia and New Zealand",
    iso: "36",
    capital_city: "Canberra"
  },
  {
    country: "Austria",
    population: "8735453",
    sq_km_area: 83859,
    life_expectancy: "77.7",
    elevation_in_meters: "910",
    continent: "Europe",
    abbreviation: "AT",
    location: "Western Europe",
    iso: "40",
    capital_city: "Wien"
  },
  {
    country: "Azerbaijan",
    population: "9827589",
    sq_km_area: 86600,
    life_expectancy: "62.9",
    elevation_in_meters: "384",
    continent: "Asia",
    abbreviation: "AZ",
    location: "Middle East",
    iso: "31",
    capital_city: "Baku"
  },
  {
    country: "Bahamas",
    population: "395361",
    sq_km_area: 13878,
    life_expectancy: "71.1",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "BS",
    location: "Caribbean",
    iso: "44",
    capital_city: "Nassau"
  },
  {
    country: "Bahrain",
    population: "1492584",
    sq_km_area: 694,
    life_expectancy: "73",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "BH",
    location: "Middle East",
    iso: "48",
    capital_city: "al-Manama"
  },
  {
    country: "Bangladesh",
    population: "164669751",
    sq_km_area: 143998,
    life_expectancy: "60.2",
    elevation_in_meters: "85",
    continent: "Asia",
    abbreviation: "BD",
    location: "Southern and Central Asia",
    iso: "50",
    capital_city: "Dhaka"
  },
  {
    country: "Barbados",
    population: "285719",
    sq_km_area: 430,
    life_expectancy: "73",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "BB",
    location: "Caribbean",
    iso: "52",
    capital_city: "Bridgetown"
  },
  {
    country: "Belarus",
    population: "9468338",
    sq_km_area: 207600,
    life_expectancy: "68",
    elevation_in_meters: "160",
    continent: "Europe",
    abbreviation: "BY",
    location: "Eastern Europe",
    iso: "112",
    capital_city: "Minsk"
  },
  {
    country: "Belgium",
    population: "11429336",
    sq_km_area: 30518,
    life_expectancy: "77.8",
    elevation_in_meters: "181",
    continent: "Europe",
    abbreviation: "BE",
    location: "Western Europe",
    iso: "56",
    capital_city: "Bruxelles [Brussel]"
  },
  {
    country: "Belize",
    population: "374681",
    sq_km_area: 22696,
    life_expectancy: "70.9",
    elevation_in_meters: "173",
    continent: "North America",
    abbreviation: "BZ",
    location: "Central America",
    iso: "84",
    capital_city: "Belmopan"
  },
  {
    country: "Benin",
    population: "11175692",
    sq_km_area: 112622,
    life_expectancy: "50.2",
    elevation_in_meters: "273",
    continent: "Africa",
    abbreviation: "BJ",
    location: "Western Africa",
    iso: "204",
    capital_city: "Porto-Novo"
  },
  {
    country: "Bermuda",
    population: "61349",
    sq_km_area: 53,
    life_expectancy: "76.9",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "BM",
    location: "North America",
    iso: "60",
    capital_city: "Hamilton"
  },
  {
    country: "Bhutan",
    population: "807610",
    sq_km_area: 47000,
    life_expectancy: "52.4",
    elevation_in_meters: "3,280",
    continent: "Asia",
    abbreviation: "BT",
    location: "Southern and Central Asia",
    iso: "64",
    capital_city: "Thimphu"
  },
  {
    country: "Bolivia",
    population: "11051600",
    sq_km_area: 1098581,
    life_expectancy: "63.7",
    elevation_in_meters: "1,192",
    continent: "South America",
    abbreviation: "BO",
    location: "South America",
    iso: "68",
    capital_city: "La Paz"
  },
  {
    country: "Bosnia and Herzegovina",
    population: "3507017",
    sq_km_area: 51197,
    life_expectancy: "71.5",
    elevation_in_meters: "500",
    continent: "Europe",
    abbreviation: "BA",
    location: "Southern Europe",
    iso: "70",
    capital_city: "Sarajevo"
  },
  {
    country: "Botswana",
    population: "2291661",
    sq_km_area: 581730,
    life_expectancy: "39.3",
    elevation_in_meters: "1,013",
    continent: "Africa",
    abbreviation: "BW",
    location: "Southern Africa",
    iso: "72",
    capital_city: "Gaborone"
  },
  {
    country: "Bouvet Island",
    population: null,
    sq_km_area: 59,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Antarctica",
    abbreviation: "BV",
    location: "Antarctica",
    iso: "74",
    capital_city: null
  },
  {
    country: "Brazil",
    population: "209288278",
    sq_km_area: 8547403,
    life_expectancy: "62.9",
    elevation_in_meters: "320",
    continent: "South America",
    abbreviation: "BR",
    location: "South America",
    iso: "76",
    capital_city: "Brasília"
  },
  {
    country: "British Indian Ocean Territory",
    population: null,
    sq_km_area: 78,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "IO",
    location: "Eastern Africa",
    iso: "86",
    capital_city: null
  },
  {
    country: "Brunei",
    population: "428697",
    sq_km_area: 5765,
    life_expectancy: "73.6",
    elevation_in_meters: "478",
    continent: "Asia",
    abbreviation: "BN",
    location: "Southeast Asia",
    iso: "96",
    capital_city: "Bandar Seri Begawan"
  },
  {
    country: "Bulgaria",
    population: "7084571",
    sq_km_area: 110994,
    life_expectancy: "70.9",
    elevation_in_meters: "472",
    continent: "Europe",
    abbreviation: "BG",
    location: "Eastern Europe",
    iso: "100",
    capital_city: "Sofia"
  },
  {
    country: "Burkina Faso",
    population: "19193382",
    sq_km_area: 274000,
    life_expectancy: "46.7",
    elevation_in_meters: "297",
    continent: "Africa",
    abbreviation: "BF",
    location: "Western Africa",
    iso: "854",
    capital_city: "Ouagadougou"
  },
  {
    country: "Burundi",
    population: "10864245",
    sq_km_area: 27834,
    life_expectancy: "46.2",
    elevation_in_meters: "1,504",
    continent: "Africa",
    abbreviation: "BI",
    location: "Eastern Africa",
    iso: "108",
    capital_city: "Bujumbura"
  },
  {
    country: "Cambodia",
    population: "16005373",
    sq_km_area: 181035,
    life_expectancy: "56.5",
    elevation_in_meters: "126",
    continent: "Asia",
    abbreviation: "KH",
    location: "Southeast Asia",
    iso: "116",
    capital_city: "Phnom Penh"
  },
  {
    country: "Cameroon",
    population: "24053727",
    sq_km_area: 475442,
    life_expectancy: "54.8",
    elevation_in_meters: "667",
    continent: "Africa",
    abbreviation: "CM",
    location: "Central Africa",
    iso: "120",
    capital_city: "Yaound"
  },
  {
    country: "Canada",
    population: "36624199",
    sq_km_area: 9970610,
    life_expectancy: "79.4",
    elevation_in_meters: "487",
    continent: "North America",
    abbreviation: "CA",
    location: "North America",
    iso: "124",
    capital_city: "Ottawa"
  },
  {
    country: "Cape Verde",
    population: "546388",
    sq_km_area: 4033,
    life_expectancy: "68.9",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "CV",
    location: "Western Africa",
    iso: "132",
    capital_city: "Praia"
  },
  {
    country: "Cayman Islands",
    population: "61559",
    sq_km_area: 264,
    life_expectancy: "78.9",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "KY",
    location: "Caribbean",
    iso: "136",
    capital_city: "George Town"
  },
  {
    country: "Central African Republic",
    population: "4659080",
    sq_km_area: 622984,
    life_expectancy: "44",
    elevation_in_meters: "635",
    continent: "Africa",
    abbreviation: "CF",
    location: "Central Africa",
    iso: "140",
    capital_city: "Bangui"
  },
  {
    country: "Chad",
    population: "14899994",
    sq_km_area: 1284000,
    life_expectancy: "50.5",
    elevation_in_meters: "543",
    continent: "Africa",
    abbreviation: "TD",
    location: "Central Africa",
    iso: "148",
    capital_city: "N'Djam"
  },
  {
    country: "Chile",
    population: "18054726",
    sq_km_area: 756626,
    life_expectancy: "75.7",
    elevation_in_meters: "1,871",
    continent: "South America",
    abbreviation: "CL",
    location: "South America",
    iso: "152",
    capital_city: "Santiago de Chile"
  },
  {
    country: "China",
    population: "1409517397",
    sq_km_area: 9572900,
    life_expectancy: "71.4",
    elevation_in_meters: "1,840",
    continent: "Asia",
    abbreviation: "CN",
    location: "Eastern Asia",
    iso: "156",
    capital_city: "Peking"
  },
  {
    country: "Christmas Island",
    population: "2500",
    sq_km_area: 135,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "CX",
    location: "Australia and New Zealand",
    iso: "162",
    capital_city: "Flying Fish Cove"
  },
  {
    country: "Cocos (Keeling) Islands",
    population: "600",
    sq_km_area: 14,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "CC",
    location: "Australia and New Zealand",
    iso: null,
    capital_city: "West Island"
  },
  {
    country: "Colombia",
    population: "49065615",
    sq_km_area: 1138914,
    life_expectancy: "70.3",
    elevation_in_meters: "593",
    continent: "South America",
    abbreviation: "CO",
    location: "South America",
    iso: "170",
    capital_city: "Santaf"
  },
  {
    country: "Comoros",
    population: "813912",
    sq_km_area: 1862,
    life_expectancy: "60",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "KM",
    location: "Eastern Africa",
    iso: "174",
    capital_city: "Moroni"
  },
  {
    country: "Congo",
    population: "5260750",
    sq_km_area: 342000,
    life_expectancy: "47.4",
    elevation_in_meters: "430",
    continent: "Africa",
    abbreviation: "CG",
    location: "Central Africa",
    iso: null,
    capital_city: "Brazzaville"
  },
  {
    country: "Cook Islands",
    population: "17380",
    sq_km_area: 236,
    life_expectancy: "71.1",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "CK",
    location: "Polynesia",
    iso: "184",
    capital_city: "Avarua"
  },
  {
    country: "Costa Rica",
    population: "4905769",
    sq_km_area: 51100,
    life_expectancy: "75.8",
    elevation_in_meters: "746",
    continent: "North America",
    abbreviation: "CR",
    location: "Central America",
    iso: "188",
    capital_city: "San Jos"
  },
  {
    country: "Croatia",
    population: "4189353",
    sq_km_area: 56538,
    life_expectancy: "73.7",
    elevation_in_meters: "331",
    continent: "Europe",
    abbreviation: "HR",
    location: "Southern Europe",
    iso: "191",
    capital_city: "Zagreb"
  },
  {
    country: "Cuba",
    population: "11484636",
    sq_km_area: 110861,
    life_expectancy: "76.2",
    elevation_in_meters: "108",
    continent: "North America",
    abbreviation: "CU",
    location: "Caribbean",
    iso: "192",
    capital_city: "La Habana"
  },
  {
    country: "Cyprus",
    population: "1179551",
    sq_km_area: 9251,
    life_expectancy: "76.7",
    elevation_in_meters: "91",
    continent: "Asia",
    abbreviation: "CY",
    location: "Middle East",
    iso: "196",
    capital_city: "Nicosia"
  },
  {
    country: "Czechia",
    population: "10618303",
    sq_km_area: 78866,
    life_expectancy: "74.5",
    elevation_in_meters: "433",
    continent: "Europe",
    abbreviation: "CZ",
    location: "Eastern Europe",
    iso: "203",
    capital_city: "Praha"
  },
  {
    country: "Denmark",
    population: "5733551",
    sq_km_area: 43094,
    life_expectancy: "76.5",
    elevation_in_meters: "34",
    continent: "Europe",
    abbreviation: "DK",
    location: "Nordic Countries",
    iso: "208",
    capital_city: "Copenhagen"
  },
  {
    country: "Djibouti",
    population: "956985",
    sq_km_area: 23200,
    life_expectancy: "50.8",
    elevation_in_meters: "430",
    continent: "Africa",
    abbreviation: "DJ",
    location: "Eastern Africa",
    iso: "262",
    capital_city: "Djibouti"
  },
  {
    country: "Dominica",
    population: "73925",
    sq_km_area: 751,
    life_expectancy: "73.4",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "DM",
    location: "Caribbean",
    iso: "212",
    capital_city: "Roseau"
  },
  {
    country: "Dominican Republic",
    population: "10766998",
    sq_km_area: 48511,
    life_expectancy: "73.2",
    elevation_in_meters: "424",
    continent: "North America",
    abbreviation: "DO",
    location: "Caribbean",
    iso: "214",
    capital_city: "Santo Domingo de Guzm"
  },
  {
    country: "East Timor",
    population: "1296311",
    sq_km_area: 14874,
    life_expectancy: "46",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "TP",
    location: "Southeast Asia",
    iso: "626",
    capital_city: "Dili"
  },
  {
    country: "Ecuador",
    population: "16624858",
    sq_km_area: 283561,
    life_expectancy: "71.1",
    elevation_in_meters: "1,117",
    continent: "South America",
    abbreviation: "EC",
    location: "South America",
    iso: "218",
    capital_city: "Quito"
  },
  {
    country: "Egypt",
    population: "97553151",
    sq_km_area: 1001449,
    life_expectancy: "63.3",
    elevation_in_meters: "321",
    continent: "Africa",
    abbreviation: "EG",
    location: "Northern Africa",
    iso: "818",
    capital_city: "Cairo"
  },
  {
    country: "El Salvador",
    population: "6377853",
    sq_km_area: 21041,
    life_expectancy: "69.7",
    elevation_in_meters: "442",
    continent: "North America",
    abbreviation: "SV",
    location: "Central America",
    iso: "222",
    capital_city: "San Salvador"
  },
  {
    country: "England",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    location: null,
    iso: null,
    capital_city: "London"
  },
  {
    country: "Equatorial Guinea",
    population: "1267689",
    sq_km_area: 28051,
    life_expectancy: "53.6",
    elevation_in_meters: "577",
    continent: "Africa",
    abbreviation: "GQ",
    location: "Central Africa",
    iso: "226",
    capital_city: "Malabo"
  },
  {
    country: "Eritrea",
    population: "5068831",
    sq_km_area: 117600,
    life_expectancy: "55.8",
    elevation_in_meters: "853",
    continent: "Africa",
    abbreviation: "ER",
    location: "Eastern Africa",
    iso: "232",
    capital_city: "Asmara"
  },
  {
    country: "Estonia",
    population: "1309632",
    sq_km_area: 45227,
    life_expectancy: "69.5",
    elevation_in_meters: "61",
    continent: "Europe",
    abbreviation: "EE",
    location: "Baltic Countries",
    iso: "233",
    capital_city: "Tallinn"
  },
  {
    country: "Ethiopia",
    population: "104957438",
    sq_km_area: 1104300,
    life_expectancy: "45.2",
    elevation_in_meters: "1,330",
    continent: "Africa",
    abbreviation: "ET",
    location: "Eastern Africa",
    iso: "231",
    capital_city: "Addis Abeba"
  },
  {
    country: "Falkland Islands",
    population: "2910",
    sq_km_area: 12173,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "South America",
    abbreviation: "FK",
    location: "South America",
    iso: "238",
    capital_city: "Stanley"
  },
  {
    country: "Faroe Islands",
    population: "49290",
    sq_km_area: 1399,
    life_expectancy: "78.4",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "FO",
    location: "Nordic Countries",
    iso: "234",
    capital_city: "Tórshavn"
  },
  {
    country: "Fiji",
    population: "905502",
    sq_km_area: 18274,
    life_expectancy: "67.9",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "FJ",
    location: "Melanesia",
    iso: null,
    capital_city: "Suva"
  },
  {
    country: "Finland",
    population: "5523231",
    sq_km_area: 338145,
    life_expectancy: "77.4",
    elevation_in_meters: "164",
    continent: "Europe",
    abbreviation: "FI",
    location: "Nordic Countries",
    iso: "246",
    capital_city: "Helsinki [Helsingfors]"
  },
  {
    country: "France",
    population: "64979548",
    sq_km_area: 551500,
    life_expectancy: "78.8",
    elevation_in_meters: "375",
    continent: "Europe",
    abbreviation: "FR",
    location: "Western Europe",
    iso: "250",
    capital_city: "Paris"
  },
  {
    country: "French Guiana",
    population: "282731",
    sq_km_area: 90000,
    life_expectancy: "76.1",
    elevation_in_meters: "168",
    continent: "South America",
    abbreviation: "GF",
    location: "South America",
    iso: "254",
    capital_city: "Cayenne"
  },
  {
    country: "French Polynesia",
    population: "283007",
    sq_km_area: 4000,
    life_expectancy: "74.8",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "PF",
    location: "Polynesia",
    iso: "258",
    capital_city: "Papeete"
  },
  {
    country: "French Southern territories",
    population: null,
    sq_km_area: 7780,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Antarctica",
    abbreviation: "TF",
    location: "Antarctica",
    iso: "260",
    capital_city: null
  },
  {
    country: "Gabon",
    population: "2025137",
    sq_km_area: 267668,
    life_expectancy: "50.1",
    elevation_in_meters: "377",
    continent: "Africa",
    abbreviation: "GA",
    location: "Central Africa",
    iso: "266",
    capital_city: "Libreville"
  },
  {
    country: "Gambia",
    population: "2100568",
    sq_km_area: 11295,
    life_expectancy: "53.2",
    elevation_in_meters: "34",
    continent: "Africa",
    abbreviation: "GM",
    location: "Western Africa",
    iso: "270",
    capital_city: "Banjul"
  },
  {
    country: "Georgia",
    population: "3912061",
    sq_km_area: 69700,
    life_expectancy: "64.5",
    elevation_in_meters: "1,432",
    continent: "Asia",
    abbreviation: "GE",
    location: "Middle East",
    iso: "268",
    capital_city: "Tbilisi"
  },
  {
    country: "Germany",
    population: "82114224",
    sq_km_area: 357022,
    life_expectancy: "77.4",
    elevation_in_meters: "263",
    continent: "Europe",
    abbreviation: "DE",
    location: "Western Europe",
    iso: "276",
    capital_city: "Berlin"
  },
  {
    country: "Ghana",
    population: "28833629",
    sq_km_area: 238533,
    life_expectancy: "57.4",
    elevation_in_meters: "190",
    continent: "Africa",
    abbreviation: "GH",
    location: "Western Africa",
    iso: "288",
    capital_city: "Accra"
  },
  {
    country: "Gibraltar",
    population: "34571",
    sq_km_area: 6,
    life_expectancy: "79",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "GI",
    location: "Southern Europe",
    iso: "292",
    capital_city: "Gibraltar"
  },
  {
    country: "Greece",
    population: "11159773",
    sq_km_area: 131626,
    life_expectancy: "78.4",
    elevation_in_meters: "498",
    continent: "Europe",
    abbreviation: "GR",
    location: "Southern Europe",
    iso: "300",
    capital_city: "Athenai"
  },
  {
    country: "Greenland",
    population: "56480",
    sq_km_area: 2166090,
    life_expectancy: "68.1",
    elevation_in_meters: "1,792",
    continent: "North America",
    abbreviation: "GL",
    location: "North America",
    iso: "304",
    capital_city: "Nuuk"
  },
  {
    country: "Grenada",
    population: "107825",
    sq_km_area: 344,
    life_expectancy: "64.5",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "GD",
    location: "Caribbean",
    iso: "308",
    capital_city: "Saint George's"
  },
  {
    country: "Guadeloupe",
    population: "449568",
    sq_km_area: 1705,
    life_expectancy: "77",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "GP",
    location: "Caribbean",
    iso: "312",
    capital_city: "Basse-Terre"
  },
  {
    country: "Gua",
    population: "164229",
    sq_km_area: 549,
    life_expectancy: "77.8",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "GU",
    location: "Micronesia",
    iso: "316",
    capital_city: "Aga"
  },
  {
    country: "Guatemala",
    population: "16913503",
    sq_km_area: 108889,
    life_expectancy: "66.2",
    elevation_in_meters: "759",
    continent: "North America",
    abbreviation: "GT",
    location: "Central America",
    iso: "320",
    capital_city: "Ciudad de Guatemala"
  },
  {
    country: "Guinea",
    population: "12717176",
    sq_km_area: 245857,
    life_expectancy: "45.6",
    elevation_in_meters: "472",
    continent: "Africa",
    abbreviation: "GN",
    location: "Western Africa",
    iso: "324",
    capital_city: "Conakry"
  },
  {
    country: "Guinea-Bissau",
    population: "1861283",
    sq_km_area: 36125,
    life_expectancy: "49",
    elevation_in_meters: "70",
    continent: "Africa",
    abbreviation: "GW",
    location: "Western Africa",
    iso: "624",
    capital_city: "Bissau"
  },
  {
    country: "Guyana",
    population: "777859",
    sq_km_area: 214969,
    life_expectancy: "64",
    elevation_in_meters: "207",
    continent: "South America",
    abbreviation: "GY",
    location: "South America",
    iso: "328",
    capital_city: "Georgetown"
  },
  {
    country: "Haiti",
    population: "10981229",
    sq_km_area: 27750,
    life_expectancy: "49.2",
    elevation_in_meters: "470",
    continent: "North America",
    abbreviation: "HT",
    location: "Caribbean",
    iso: "332",
    capital_city: "Port-au-Prince"
  },
  {
    country: "Heard Island and McDonald Islands",
    population: null,
    sq_km_area: 359,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Antarctica",
    abbreviation: "HM",
    location: "Antarctica",
    iso: "334",
    capital_city: null
  },
  {
    country: "Holy See",
    population: "1000",
    sq_km_area: 0.4,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "VA",
    location: "Southern Europe",
    iso: null,
    capital_city: "Citt"
  },
  {
    country: "Honduras",
    population: "9265067",
    sq_km_area: 112088,
    life_expectancy: "69.9",
    elevation_in_meters: "684",
    continent: "North America",
    abbreviation: "HN",
    location: "Central America",
    iso: "340",
    capital_city: "Tegucigalpa"
  },
  {
    country: "Hong Kong",
    population: "7364883",
    sq_km_area: 1075,
    life_expectancy: "79.5",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "HK",
    location: "Eastern Asia",
    iso: "344",
    capital_city: "Victoria"
  },
  {
    country: "Hungary",
    population: "9721559",
    sq_km_area: 93030,
    life_expectancy: "71.4",
    elevation_in_meters: "143",
    continent: "Europe",
    abbreviation: "HU",
    location: "Eastern Europe",
    iso: "348",
    capital_city: "Budapest"
  },
  {
    country: "Iceland",
    population: "335025",
    sq_km_area: 103000,
    life_expectancy: "79.4",
    elevation_in_meters: "557",
    continent: "Europe",
    abbreviation: "IS",
    location: "Nordic Countries",
    iso: "352",
    capital_city: "Reykjav"
  },
  {
    country: "India",
    population: "1339180127",
    sq_km_area: 3287263,
    life_expectancy: "62.5",
    elevation_in_meters: "160",
    continent: "Asia",
    abbreviation: "IN",
    location: "Southern and Central Asia",
    iso: "356",
    capital_city: "New Delhi"
  },
  {
    country: "Indonesia",
    population: "263991379",
    sq_km_area: 1904569,
    life_expectancy: "70.1",
    elevation_in_meters: "367",
    continent: "Asia",
    abbreviation: "ID",
    location: "Southeast Asia",
    iso: "360",
    capital_city: "Jakarta"
  },
  {
    country: "Iran",
    population: "81162788",
    sq_km_area: 1648195,
    life_expectancy: "69.7",
    elevation_in_meters: "1,305",
    continent: "Asia",
    abbreviation: "IR",
    location: "Southern and Central Asia",
    iso: "364",
    capital_city: "Tehran"
  },
  {
    country: "Iraq",
    population: "38274618",
    sq_km_area: 438317,
    life_expectancy: "66.5",
    elevation_in_meters: "312",
    continent: "Asia",
    abbreviation: "IQ",
    location: "Middle East",
    iso: "368",
    capital_city: "Baghdad"
  },
  {
    country: "Ireland",
    population: "4761657",
    sq_km_area: 70273,
    life_expectancy: "76.8",
    elevation_in_meters: "118",
    continent: "Europe",
    abbreviation: "IE",
    location: "British Isles",
    iso: "372",
    capital_city: "Dublin"
  },
  {
    country: "Israel",
    population: "8321570",
    sq_km_area: 21056,
    life_expectancy: "78.6",
    elevation_in_meters: "508",
    continent: "Asia",
    abbreviation: "IL",
    location: "Middle East",
    iso: "376",
    capital_city: "Jerusalem"
  },
  {
    country: "Italy",
    population: "59359900",
    sq_km_area: 301316,
    life_expectancy: "79",
    elevation_in_meters: "538",
    continent: "Europe",
    abbreviation: "IT",
    location: "Southern Europe",
    iso: "380",
    capital_city: "Roma"
  },
  {
    country: "Cote d'Ivoire",
    population: "24294750",
    sq_km_area: 322463,
    life_expectancy: "45.2",
    elevation_in_meters: "250",
    continent: "Africa",
    abbreviation: "CI",
    location: "Western Africa",
    iso: "384",
    capital_city: "Yamoussoukro"
  },
  {
    country: "Jamaica",
    population: "2890299",
    sq_km_area: 10990,
    life_expectancy: "75.2",
    elevation_in_meters: "18",
    continent: "North America",
    abbreviation: "JM",
    location: "Caribbean",
    iso: "388",
    capital_city: "Kingston"
  },
  {
    country: "Japan",
    population: "127484450",
    sq_km_area: 377829,
    life_expectancy: "80.7",
    elevation_in_meters: "438",
    continent: "Asia",
    abbreviation: "JP",
    location: "Eastern Asia",
    iso: "392",
    capital_city: "Tokyo"
  },
  {
    country: "Jordan",
    population: "9702353",
    sq_km_area: 88946,
    life_expectancy: "77.4",
    elevation_in_meters: "812",
    continent: "Asia",
    abbreviation: "JO",
    location: "Middle East",
    iso: "400",
    capital_city: "Amman"
  },
  {
    country: "Kazakhstan",
    population: "18204499",
    sq_km_area: 2724900,
    life_expectancy: "63.2",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "KZ",
    location: "Southern and Central Asia",
    iso: null,
    capital_city: "Astana"
  },
  {
    country: "Kenya",
    population: "49699862",
    sq_km_area: 580367,
    life_expectancy: "48",
    elevation_in_meters: "762",
    continent: "Africa",
    abbreviation: "KE",
    location: "Eastern Africa",
    iso: "404",
    capital_city: "Nairobi"
  },
  {
    country: "Kiribati",
    population: "116398",
    sq_km_area: 726,
    life_expectancy: "59.8",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "KI",
    location: "Micronesia",
    iso: "296",
    capital_city: "Bairiki"
  },
  {
    country: "Kuwait",
    population: "4136528",
    sq_km_area: 17818,
    life_expectancy: "76.1",
    elevation_in_meters: "108",
    continent: "Asia",
    abbreviation: "KW",
    location: "Middle East",
    iso: "414",
    capital_city: "Kuwait"
  },
  {
    country: "Kyrgyzstan",
    population: "6045117",
    sq_km_area: 199900,
    life_expectancy: "63.4",
    elevation_in_meters: "2,988",
    continent: "Asia",
    abbreviation: "KG",
    location: "Southern and Central Asia",
    iso: "417",
    capital_city: "Bishkek"
  },
  {
    country: "Laos",
    population: "6858160",
    sq_km_area: 236800,
    life_expectancy: "53.1",
    elevation_in_meters: "710",
    continent: "Asia",
    abbreviation: "LA",
    location: "Southeast Asia",
    iso: "418",
    capital_city: "Vientiane"
  },
  {
    country: "Latvia",
    population: "1949670",
    sq_km_area: 64589,
    life_expectancy: "68.4",
    elevation_in_meters: "87",
    continent: "Europe",
    abbreviation: "LV",
    location: "Baltic Countries",
    iso: "428",
    capital_city: "Riga"
  },
  {
    country: "Lebanon",
    population: "6082357",
    sq_km_area: 10400,
    life_expectancy: "71.3",
    elevation_in_meters: "1,250",
    continent: "Asia",
    abbreviation: "LB",
    location: "Middle East",
    iso: "422",
    capital_city: "Beirut"
  },
  {
    country: "Lesotho",
    population: "2233339",
    sq_km_area: 30355,
    life_expectancy: "50.8",
    elevation_in_meters: "2,161",
    continent: "Africa",
    abbreviation: "LS",
    location: "Southern Africa",
    iso: "426",
    capital_city: "Maseru"
  },
  {
    country: "Liberia",
    population: "4731906",
    sq_km_area: 111369,
    life_expectancy: "51",
    elevation_in_meters: "243",
    continent: "Africa",
    abbreviation: "LR",
    location: "Western Africa",
    iso: "430",
    capital_city: "Monrovia"
  },
  {
    country: "Libya",
    population: "5605000",
    sq_km_area: 1759540,
    life_expectancy: "75.5",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "LY",
    location: "Northern Africa",
    iso: null,
    capital_city: "Tripoli"
  },
  {
    country: "Liechtenstein",
    population: "37922",
    sq_km_area: 160,
    life_expectancy: "78.8",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "LI",
    location: "Western Europe",
    iso: "438",
    capital_city: "Vaduz"
  },
  {
    country: "Lithuania",
    population: "2890297",
    sq_km_area: 65301,
    life_expectancy: "69.1",
    elevation_in_meters: "110",
    continent: "Europe",
    abbreviation: "LT",
    location: "Baltic Countries",
    iso: "440",
    capital_city: "Vilnius"
  },
  {
    country: "Luxembourg",
    population: "583455",
    sq_km_area: 2586,
    life_expectancy: "77.1",
    elevation_in_meters: "325",
    continent: "Europe",
    abbreviation: "LU",
    location: "Western Europe",
    iso: "442",
    capital_city: "Luxembourg [Luxemburg/L"
  },
  {
    country: "Macao",
    population: "473000",
    sq_km_area: 18,
    life_expectancy: "81.6",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "MO",
    location: "Eastern Asia",
    iso: "446",
    capital_city: "Macao"
  },
  {
    country: "North Macedonia",
    population: "2024000",
    sq_km_area: 25713,
    life_expectancy: "73.8",
    elevation_in_meters: "741",
    continent: "Europe",
    abbreviation: "MK",
    location: "Southern Europe",
    iso: "807",
    capital_city: "Skopje"
  },
  {
    country: "Madagascar",
    population: "25570895",
    sq_km_area: 587041,
    life_expectancy: "55",
    elevation_in_meters: "615",
    continent: "Africa",
    abbreviation: "MG",
    location: "Eastern Africa",
    iso: "450",
    capital_city: "Antananarivo"
  },
  {
    country: "Malawi",
    population: "18622104",
    sq_km_area: 118484,
    life_expectancy: "37.6",
    elevation_in_meters: "779",
    continent: "Africa",
    abbreviation: "MW",
    location: "Eastern Africa",
    iso: "454",
    capital_city: "Lilongwe"
  },
  {
    country: "Malaysia",
    population: "31624264",
    sq_km_area: 329758,
    life_expectancy: "70.8",
    elevation_in_meters: "538",
    continent: "Asia",
    abbreviation: "MY",
    location: "Southeast Asia",
    iso: "458",
    capital_city: "Kuala Lumpur"
  },
  {
    country: "Maldives",
    population: "436330",
    sq_km_area: 298,
    life_expectancy: "62.2",
    elevation_in_meters: "1.8",
    continent: "Asia",
    abbreviation: "MV",
    location: "Southern and Central Asia",
    iso: "462",
    capital_city: "Male"
  },
  {
    country: "Mali",
    population: "18541980",
    sq_km_area: 1240192,
    life_expectancy: "46.7",
    elevation_in_meters: "343",
    continent: "Africa",
    abbreviation: "ML",
    location: "Western Africa",
    iso: "466",
    capital_city: "Bamako"
  },
  {
    country: "Malta",
    population: "430835",
    sq_km_area: 316,
    life_expectancy: "77.9",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "MT",
    location: "Southern Europe",
    iso: "470",
    capital_city: "Valletta"
  },
  {
    country: "Marshall Islands",
    population: "53127",
    sq_km_area: 181,
    life_expectancy: "65.5",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "MH",
    location: "Micronesia",
    iso: "584",
    capital_city: "Dalap-Uliga-Darrit"
  },
  {
    country: "Martinique",
    population: "384896",
    sq_km_area: 1102,
    life_expectancy: "78.3",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "MQ",
    location: "Caribbean",
    iso: "474",
    capital_city: "Fort-de-France"
  },
  {
    country: "Mauritania",
    population: "4420184",
    sq_km_area: 1025520,
    life_expectancy: "50.8",
    elevation_in_meters: "276",
    continent: "Africa",
    abbreviation: "MR",
    location: "Western Africa",
    iso: "478",
    capital_city: "Nouakchott"
  },
  {
    country: "Mauritius",
    population: "1265138",
    sq_km_area: 2040,
    life_expectancy: "71",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "MU",
    location: "Eastern Africa",
    iso: "480",
    capital_city: "Port-Louis"
  },
  {
    country: "Mayotte",
    population: "253045",
    sq_km_area: 373,
    life_expectancy: "59.5",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "YT",
    location: "Eastern Africa",
    iso: "175",
    capital_city: "Mamoutzou"
  },
  {
    country: "Mexico",
    population: "129163276",
    sq_km_area: 1958201,
    life_expectancy: "71.5",
    elevation_in_meters: "1,111",
    continent: "North America",
    abbreviation: "MX",
    location: "Central America",
    iso: "484",
    capital_city: "Ciudad de M"
  },
  {
    country: "Micronesia, Federated States of",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "FM",
    location: "Micronesia",
    iso: null,
    capital_city: "Palikir"
  },
  {
    country: "Moldova",
    population: "4051212",
    sq_km_area: 33851,
    life_expectancy: "64.5",
    elevation_in_meters: "139",
    continent: "Europe",
    abbreviation: "MD",
    location: "Eastern Europe",
    iso: "498",
    capital_city: "Chisinau"
  },
  {
    country: "Monaco",
    population: "38695",
    sq_km_area: 1.5,
    life_expectancy: "78.8",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "MC",
    location: "Western Europe",
    iso: "492",
    capital_city: "Monaco-Ville"
  },
  {
    country: "Mongolia",
    population: "3075647",
    sq_km_area: 1566500,
    life_expectancy: "67.3",
    elevation_in_meters: "1,528",
    continent: "Asia",
    abbreviation: "MN",
    location: "Eastern Asia",
    iso: "496",
    capital_city: "Ulan Bator"
  },
  {
    country: "Montserrat",
    population: "5177",
    sq_km_area: 102,
    life_expectancy: "78",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "MS",
    location: "Caribbean",
    iso: "500",
    capital_city: "Plymouth"
  },
  {
    country: "Morocco",
    population: "35739580",
    sq_km_area: 446550,
    life_expectancy: "69.1",
    elevation_in_meters: "909",
    continent: "Africa",
    abbreviation: "MA",
    location: "Northern Africa",
    iso: "504",
    capital_city: "Rabat"
  },
  {
    country: "Mozambique",
    population: "29668834",
    sq_km_area: 801590,
    life_expectancy: "37.5",
    elevation_in_meters: "345",
    continent: "Africa",
    abbreviation: "MZ",
    location: "Eastern Africa",
    iso: "508",
    capital_city: "Maputo"
  },
  {
    country: "Myanmar",
    population: "53370609",
    sq_km_area: 676578,
    life_expectancy: "54.9",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "MM",
    location: "Southeast Asia",
    iso: null,
    capital_city: "Rangoon (Yangon)"
  },
  {
    country: "Namibia",
    population: "2533794",
    sq_km_area: 824292,
    life_expectancy: "42.5",
    elevation_in_meters: "1,141",
    continent: "Africa",
    abbreviation: "NA",
    location: "Southern Africa",
    iso: "516",
    capital_city: "Windhoek"
  },
  {
    country: "Nauru",
    population: "11359",
    sq_km_area: 21,
    life_expectancy: "60.8",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "NR",
    location: "Micronesia",
    iso: "520",
    capital_city: "Yaren"
  },
  {
    country: "Nepal",
    population: "29304998",
    sq_km_area: 147181,
    life_expectancy: "57.8",
    elevation_in_meters: "3,265",
    continent: "Asia",
    abbreviation: "NP",
    location: "Southern and Central Asia",
    iso: "524",
    capital_city: "Kathmandu"
  },
  {
    country: "Netherlands",
    population: "17035938",
    sq_km_area: 41526,
    life_expectancy: "78.3",
    elevation_in_meters: "30",
    continent: "Europe",
    abbreviation: "NL",
    location: "Western Europe",
    iso: "528",
    capital_city: "Amsterdam"
  },
  {
    country: "Netherlands Antilles",
    population: "217000",
    sq_km_area: 800,
    life_expectancy: "74.7",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "AN",
    location: "Caribbean",
    iso: null,
    capital_city: "Willemstad"
  },
  {
    country: "New Caledonia",
    population: "276255",
    sq_km_area: 18575,
    life_expectancy: "72.8",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "NC",
    location: "Melanesia",
    iso: "540",
    capital_city: "Noum"
  },
  {
    country: "New Zealand",
    population: "4705818",
    sq_km_area: 270534,
    life_expectancy: "77.8",
    elevation_in_meters: "388",
    continent: "Oceania",
    abbreviation: "NZ",
    location: "Australia and New Zealand",
    iso: "554",
    capital_city: "Wellington"
  },
  {
    country: "Nicaragua",
    population: "6217581",
    sq_km_area: 130000,
    life_expectancy: "68.7",
    elevation_in_meters: "298",
    continent: "North America",
    abbreviation: "NI",
    location: "Central America",
    iso: "558",
    capital_city: "Managua"
  },
  {
    country: "Niger",
    population: "21477348",
    sq_km_area: 1267000,
    life_expectancy: "41.3",
    elevation_in_meters: "474",
    continent: "Africa",
    abbreviation: "NE",
    location: "Western Africa",
    iso: "562",
    capital_city: "Niamey"
  },
  {
    country: "Nigeria",
    population: "190886311",
    sq_km_area: 923768,
    life_expectancy: "51.6",
    elevation_in_meters: "380",
    continent: "Africa",
    abbreviation: "NG",
    location: "Western Africa",
    iso: "566",
    capital_city: "Abuja"
  },
  {
    country: "Niue",
    population: "1618",
    sq_km_area: 260,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "NU",
    location: "Polynesia",
    iso: "570",
    capital_city: "Alofi"
  },
  {
    country: "Norfolk Island",
    population: "2000",
    sq_km_area: 36,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "NF",
    location: "Australia and New Zealand",
    iso: "574",
    capital_city: "Kingston"
  },
  {
    country: "Korea, North",
    population: "25490965",
    sq_km_area: 120538,
    life_expectancy: "70.7",
    elevation_in_meters: "400",
    continent: "Asia",
    abbreviation: "KP",
    location: "Eastern Asia",
    iso: "408",
    capital_city: "Pyongyang"
  },
  {
    country: "Northern Ireland",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "GB",
    location: null,
    iso: null,
    capital_city: "Belfast"
  },
  {
    country: "Northern Mariana Islands",
    population: "55144",
    sq_km_area: 464,
    life_expectancy: "75.5",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "MP",
    location: "Micronesia",
    iso: "580",
    capital_city: "Garapan"
  },
  {
    country: "Norway",
    population: "5305383",
    sq_km_area: 323877,
    life_expectancy: "78.7",
    elevation_in_meters: "460",
    continent: "Europe",
    abbreviation: "NO",
    location: "Nordic Countries",
    iso: "578",
    capital_city: "Oslo"
  },
  {
    country: "Oman",
    population: "4636262",
    sq_km_area: 309500,
    life_expectancy: "71.8",
    elevation_in_meters: "310",
    continent: "Asia",
    abbreviation: "OM",
    location: "Middle East",
    iso: "512",
    capital_city: "Masqat"
  },
  {
    country: "Pakistan",
    population: "197015955",
    sq_km_area: 796095,
    life_expectancy: "61.1",
    elevation_in_meters: "900",
    continent: "Asia",
    abbreviation: "PK",
    location: "Southern and Central Asia",
    iso: "586",
    capital_city: "Islamabad"
  },
  {
    country: "Palau",
    population: "21729",
    sq_km_area: 459,
    life_expectancy: "68.6",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "PW",
    location: "Micronesia",
    iso: "585",
    capital_city: "Koror"
  },
  {
    country: "Palestine",
    population: "4920724",
    sq_km_area: 6257,
    life_expectancy: "71.4",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "PS",
    location: "Middle East",
    iso: "275",
    capital_city: "Gaza"
  },
  {
    country: "Panama",
    population: "4098587",
    sq_km_area: 75517,
    life_expectancy: "75.5",
    elevation_in_meters: "360",
    continent: "North America",
    abbreviation: "PA",
    location: "Central America",
    iso: "591",
    capital_city: "Ciudad de Panam"
  },
  {
    country: "Papua New Guinea",
    population: "8251162",
    sq_km_area: 462840,
    life_expectancy: "63.1",
    elevation_in_meters: "667",
    continent: "Oceania",
    abbreviation: "PG",
    location: "Melanesia",
    iso: "598",
    capital_city: "Port Moresby"
  },
  {
    country: "Paraguay",
    population: "6811297",
    sq_km_area: 406752,
    life_expectancy: "73.7",
    elevation_in_meters: "178",
    continent: "South America",
    abbreviation: "PY",
    location: "South America",
    iso: "600",
    capital_city: "Asunci"
  },
  {
    country: "Peru",
    population: "32165485",
    sq_km_area: 1285216,
    life_expectancy: "70",
    elevation_in_meters: "1,555",
    continent: "South America",
    abbreviation: "PE",
    location: "South America",
    iso: "604",
    capital_city: "Lima"
  },
  {
    country: "Philippines",
    population: "104918090",
    sq_km_area: 300000,
    life_expectancy: "67.5",
    elevation_in_meters: "442",
    continent: "Asia",
    abbreviation: "PH",
    location: "Southeast Asia",
    iso: "608",
    capital_city: "Manila"
  },
  {
    country: "Pitcairn",
    population: "50",
    sq_km_area: 49,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "PN",
    location: "Polynesia",
    iso: null,
    capital_city: "Adamstown"
  },
  {
    country: "Poland",
    population: "38170712",
    sq_km_area: 323250,
    life_expectancy: "73.2",
    elevation_in_meters: "173",
    continent: "Europe",
    abbreviation: "PL",
    location: "Eastern Europe",
    iso: "616",
    capital_city: "Warszawa"
  },
  {
    country: "Portugal",
    population: "10329506",
    sq_km_area: 91982,
    life_expectancy: "75.8",
    elevation_in_meters: "372",
    continent: "Europe",
    abbreviation: "PT",
    location: "Southern Europe",
    iso: "620",
    capital_city: "Lisboa"
  },
  {
    country: "Puerto Rico",
    population: "3663131",
    sq_km_area: 8875,
    life_expectancy: "75.6",
    elevation_in_meters: "261",
    continent: "North America",
    abbreviation: "PR",
    location: "Caribbean",
    iso: "630",
    capital_city: "San Juan"
  },
  {
    country: "Qatar",
    population: "2639211",
    sq_km_area: 11000,
    life_expectancy: "72.4",
    elevation_in_meters: "28",
    continent: "Asia",
    abbreviation: "QA",
    location: "Middle East",
    iso: "634",
    capital_city: "Doha"
  },
  {
    country: "Reunion",
    population: "699000",
    sq_km_area: 2510,
    life_expectancy: "72.7",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "RE",
    location: "Eastern Africa",
    iso: "638",
    capital_city: "Saint-Denis"
  },
  {
    country: "Romania",
    population: "19679306",
    sq_km_area: 238391,
    life_expectancy: "69.9",
    elevation_in_meters: "414",
    continent: "Europe",
    abbreviation: "RO",
    location: "Eastern Europe",
    iso: "642",
    capital_city: "Bucuresti"
  },
  {
    country: "Russia",
    population: "143989754",
    sq_km_area: 17075400,
    life_expectancy: "67.2",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "RU",
    location: "Eastern Europe",
    iso: null,
    capital_city: "Moscow"
  },
  {
    country: "Rwanda",
    population: "12208407",
    sq_km_area: 26338,
    life_expectancy: "39.3",
    elevation_in_meters: "1,598",
    continent: "Africa",
    abbreviation: "RW",
    location: "Eastern Africa",
    iso: "646",
    capital_city: "Kigali"
  },
  {
    country: "Saint Helena",
    population: "4049",
    sq_km_area: 314,
    life_expectancy: "76.8",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "SH",
    location: "Western Africa",
    iso: "654",
    capital_city: "Jamestown"
  },
  {
    country: "Saint Kitts and Nevis",
    population: "55345",
    sq_km_area: 261,
    life_expectancy: "70.7",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "KN",
    location: "Caribbean",
    iso: "659",
    capital_city: "Basseterre"
  },
  {
    country: "Saint Lucia",
    population: "178844",
    sq_km_area: 622,
    life_expectancy: "72.3",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "LC",
    location: "Caribbean",
    iso: "662",
    capital_city: "Castries"
  },
  {
    country: "Saint Pierre and Miquelon",
    population: "6320",
    sq_km_area: 242,
    life_expectancy: "77.6",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "PM",
    location: "North America",
    iso: "666",
    capital_city: "Saint-Pierre"
  },
  {
    country: "Saint Vincent and the Grenadines",
    population: "109897",
    sq_km_area: 388,
    life_expectancy: "72.3",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "VC",
    location: "Caribbean",
    iso: "670",
    capital_city: "Kingstown"
  },
  {
    country: "Samoa",
    population: "196440",
    sq_km_area: 2831,
    life_expectancy: "69.2",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "WS",
    location: "Polynesia",
    iso: "882",
    capital_city: "Apia"
  },
  {
    country: "San Marino",
    population: "33400",
    sq_km_area: 61,
    life_expectancy: "81.1",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "SM",
    location: "Southern Europe",
    iso: "674",
    capital_city: "San Marino"
  },
  {
    country: "Sao Tome and Principe",
    population: "204327",
    sq_km_area: 964,
    life_expectancy: "65.3",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "ST",
    location: "Central Africa",
    iso: "678",
    capital_city: "S"
  },
  {
    country: "Saudi Arabia",
    population: "32938213",
    sq_km_area: 2149690,
    life_expectancy: "67.8",
    elevation_in_meters: "665",
    continent: "Asia",
    abbreviation: "SA",
    location: "Middle East",
    iso: "682",
    capital_city: "Riyadh"
  },
  {
    country: "Scotland",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    location: null,
    iso: null,
    capital_city: "Edinburgh"
  },
  {
    country: "Senegal",
    population: "15850567",
    sq_km_area: 196722,
    life_expectancy: "62.2",
    elevation_in_meters: "69",
    continent: "Africa",
    abbreviation: "SN",
    location: "Western Africa",
    iso: "686",
    capital_city: "Dakar"
  },
  {
    country: "Seychelles",
    population: "94737",
    sq_km_area: 455,
    life_expectancy: "70.4",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "SC",
    location: "Eastern Africa",
    iso: "690",
    capital_city: "Victoria"
  },
  {
    country: "Sierra Leone",
    population: "7557212",
    sq_km_area: 71740,
    life_expectancy: "45.3",
    elevation_in_meters: "279",
    continent: "Africa",
    abbreviation: "SL",
    location: "Western Africa",
    iso: "694",
    capital_city: "Freetown"
  },
  {
    country: "Singapore",
    population: "5708844",
    sq_km_area: 618,
    life_expectancy: "80.1",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "SG",
    location: "Southeast Asia",
    iso: "702",
    capital_city: "Singapore"
  },
  {
    country: "Slovakia",
    population: "5447662",
    sq_km_area: 49012,
    life_expectancy: "73.7",
    elevation_in_meters: "458",
    continent: "Europe",
    abbreviation: "SK",
    location: "Eastern Europe",
    iso: "703",
    capital_city: "Bratislava"
  },
  {
    country: "Slovenia",
    population: "2079976",
    sq_km_area: 20256,
    life_expectancy: "74.9",
    elevation_in_meters: "492",
    continent: "Europe",
    abbreviation: "SI",
    location: "Southern Europe",
    iso: "705",
    capital_city: "Ljubljana"
  },
  {
    country: "Solomon Islands",
    population: "611343",
    sq_km_area: 28896,
    life_expectancy: "71.3",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "SB",
    location: "Melanesia",
    iso: "90",
    capital_city: "Honiara"
  },
  {
    country: "Somalia",
    population: "14742523",
    sq_km_area: 637657,
    life_expectancy: "46.2",
    elevation_in_meters: "410",
    continent: "Africa",
    abbreviation: "SO",
    location: "Eastern Africa",
    iso: "706",
    capital_city: "Mogadishu"
  },
  {
    country: "South Africa",
    population: "56717156",
    sq_km_area: 1221037,
    life_expectancy: "51.1",
    elevation_in_meters: "1,034",
    continent: "Africa",
    abbreviation: "ZA",
    location: "Southern Africa",
    iso: "710",
    capital_city: "Pretoria"
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    population: null,
    sq_km_area: 3903,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Antarctica",
    abbreviation: "GS",
    location: "Antarctica",
    iso: "239",
    capital_city: null
  },
  {
    country: "Korea, South",
    population: "50982212",
    sq_km_area: 99434,
    life_expectancy: "74.4",
    elevation_in_meters: "282",
    continent: "Asia",
    abbreviation: "KR",
    location: "Eastern Asia",
    iso: "410",
    capital_city: "Seoul"
  },
  {
    country: "South Sudan",
    population: "12575714",
    sq_km_area: 619745,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "SS",
    location: "Eastern Africa",
    iso: "728",
    capital_city: "Juba"
  },
  {
    country: "Spain",
    population: "46354321",
    sq_km_area: 505992,
    life_expectancy: "78.8",
    elevation_in_meters: "660",
    continent: "Europe",
    abbreviation: "ES",
    location: "Southern Europe",
    iso: "724",
    capital_city: "Madrid"
  },
  {
    country: "Sri Lanka",
    population: "20876917",
    life_expectancy: null,
    elevation_in_meters: null,
    location: null,
    iso: null,
    capital_city: null
  },
  {
    country: "Sudan",
    population: "40533330",
    sq_km_area: 1886068,
    life_expectancy: "56.6",
    elevation_in_meters: "568",
    continent: "Africa",
    abbreviation: "SD",
    location: "Northern Africa",
    iso: "729",
    capital_city: "Khartum"
  },
  {
    country: "Suriname",
    population: "563402",
    sq_km_area: 163265,
    life_expectancy: "71.4",
    elevation_in_meters: "246",
    continent: "South America",
    abbreviation: "SR",
    location: "South America",
    iso: "740",
    capital_city: "Paramaribo"
  },
  {
    country: "Svalbard and Jan Mayen",
    population: "3200",
    sq_km_area: 62422,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "SJ",
    location: "Nordic Countries",
    iso: "744",
    capital_city: "Longyearbyen"
  },
  {
    country: "Swaziland",
    population: "1008000",
    sq_km_area: 17364,
    life_expectancy: "40.4",
    elevation_in_meters: "305",
    continent: "Africa",
    abbreviation: "SZ",
    location: "Southern Africa",
    iso: "748",
    capital_city: "Mbabane"
  },
  {
    country: "Sweden",
    population: "9910701",
    sq_km_area: 449964,
    life_expectancy: "79.6",
    elevation_in_meters: "320",
    continent: "Europe",
    abbreviation: "SE",
    location: "Nordic Countries",
    iso: "752",
    capital_city: "Stockholm"
  },
  {
    country: "Switzerland",
    population: "8476005",
    sq_km_area: 41284,
    life_expectancy: "79.6",
    elevation_in_meters: "1,350",
    continent: "Europe",
    abbreviation: "CH",
    location: "Western Europe",
    iso: "756",
    capital_city: "Bern"
  },
  {
    country: "Syria",
    population: "18269868",
    sq_km_area: 185180,
    life_expectancy: "68.5",
    elevation_in_meters: "514",
    continent: "Asia",
    abbreviation: "SY",
    location: "Middle East",
    iso: "760",
    capital_city: "Damascus"
  },
  {
    country: "Tajikistan",
    population: "8921343",
    sq_km_area: 143100,
    life_expectancy: "64.1",
    elevation_in_meters: "3,186",
    continent: "Asia",
    abbreviation: "TJ",
    location: "Southern and Central Asia",
    iso: "762",
    capital_city: "Dushanbe"
  },
  {
    country: "Tanzania",
    population: "57310019",
    sq_km_area: 883749,
    life_expectancy: "52.3",
    elevation_in_meters: "1,018",
    continent: "Africa",
    abbreviation: "TZ",
    location: "Eastern Africa",
    iso: "834",
    capital_city: "Dodoma"
  },
  {
    country: "Thailand",
    population: "69037513",
    sq_km_area: 513115,
    life_expectancy: "68.6",
    elevation_in_meters: "287",
    continent: "Asia",
    abbreviation: "TH",
    location: "Southeast Asia",
    iso: "764",
    capital_city: "Bangkok"
  },
  {
    country: "The Democratic Republic of Congo",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "CD",
    location: null,
    iso: null,
    capital_city: null
  },
  {
    country: "Togo",
    population: "7797694",
    sq_km_area: 56785,
    life_expectancy: "54.7",
    elevation_in_meters: "236",
    continent: "Africa",
    abbreviation: "TG",
    location: "Western Africa",
    iso: "768",
    capital_city: "Lom"
  },
  {
    country: "Tokelau",
    population: "1300",
    sq_km_area: 12,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "TK",
    location: "Polynesia",
    iso: "772",
    capital_city: "Fakaofo"
  },
  {
    country: "Tonga",
    population: "108020",
    sq_km_area: 650,
    life_expectancy: "67.9",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "TO",
    location: "Polynesia",
    iso: "776",
    capital_city: "Nuku'alofa"
  },
  {
    country: "Trinidad and Tobago",
    population: "1369125",
    sq_km_area: 5130,
    life_expectancy: "68",
    elevation_in_meters: "83",
    continent: "North America",
    abbreviation: "TT",
    location: "Caribbean",
    iso: "780",
    capital_city: "Port-of-Spain"
  },
  {
    country: "Tunisia",
    population: "11532127",
    sq_km_area: 163610,
    life_expectancy: "73.7",
    elevation_in_meters: "246",
    continent: "Africa",
    abbreviation: "TN",
    location: "Northern Africa",
    iso: "788",
    capital_city: "Tunis"
  },
  {
    country: "Turkey",
    population: "80745020",
    sq_km_area: 774815,
    life_expectancy: "71",
    elevation_in_meters: "1,132",
    continent: "Asia",
    abbreviation: "TR",
    location: "Middle East",
    iso: "792",
    capital_city: "Ankara"
  },
  {
    country: "Turkmenistan",
    population: "5758075",
    sq_km_area: 488100,
    life_expectancy: "60.9",
    elevation_in_meters: "230",
    continent: "Asia",
    abbreviation: "TM",
    location: "Southern and Central Asia",
    iso: "795",
    capital_city: "Ashgabat"
  },
  {
    country: "Turks and Caicos Islands",
    population: "35446",
    sq_km_area: 430,
    life_expectancy: "73.3",
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "TC",
    location: "Caribbean",
    iso: "796",
    capital_city: "Cockburn Town"
  },
  {
    country: "Tuvalu",
    population: "11192",
    sq_km_area: 26,
    life_expectancy: "66.3",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "TV",
    location: "Polynesia",
    iso: "798",
    capital_city: "Funafuti"
  },
  {
    country: "Uganda",
    population: "42862958",
    sq_km_area: 241038,
    life_expectancy: "42.9",
    elevation_in_meters: null,
    continent: "Africa",
    abbreviation: "UG",
    location: "Eastern Africa",
    iso: "800",
    capital_city: "Kampala"
  },
  {
    country: "Ukraine",
    population: "44222947",
    sq_km_area: 603700,
    life_expectancy: "66",
    elevation_in_meters: "175",
    continent: "Europe",
    abbreviation: "UA",
    location: "Eastern Europe",
    iso: "804",
    capital_city: "Kyiv"
  },
  {
    country: "United Arab Emirates",
    population: "9400145",
    sq_km_area: 83600,
    life_expectancy: "74.1",
    elevation_in_meters: "149",
    continent: "Asia",
    abbreviation: "AE",
    location: "Middle East",
    iso: "784",
    capital_city: "Abu Dhabi"
  },
  {
    country: "United Kingdom",
    population: "66181585",
    sq_km_area: 242900,
    life_expectancy: "77.7",
    elevation_in_meters: "162",
    continent: "Europe",
    abbreviation: "GB",
    location: "British Isles",
    iso: "826",
    capital_city: "London"
  },
  {
    country: "US",
    population: "324459463",
    sq_km_area: 9363520,
    life_expectancy: "77.1",
    elevation_in_meters: "760",
    continent: "North America",
    abbreviation: "US",
    location: "North America",
    iso: "840",
    capital_city: "Washington"
  },
  {
    country: "United States Minor Outlying Islands",
    population: null,
    sq_km_area: 16,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "UM",
    location: "Micronesia/Caribbean",
    iso: null,
    capital_city: null
  },
  {
    country: "Uruguay",
    population: "3456750",
    sq_km_area: 175016,
    life_expectancy: "75.2",
    elevation_in_meters: "109",
    continent: "South America",
    abbreviation: "UY",
    location: "South America",
    iso: "858",
    capital_city: "Montevideo"
  },
  {
    country: "Uzbekistan",
    population: "31910641",
    sq_km_area: 447400,
    life_expectancy: "63.7",
    elevation_in_meters: null,
    continent: "Asia",
    abbreviation: "UZ",
    location: "Southern and Central Asia",
    iso: "860",
    capital_city: "Toskent"
  },
  {
    country: "Vanuatu",
    population: "276244",
    sq_km_area: 12189,
    life_expectancy: "60.6",
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "VU",
    location: "Melanesia",
    iso: "548",
    capital_city: "Port-Vila"
  },
  {
    country: "Venezuela",
    population: "31977065",
    sq_km_area: 912050,
    life_expectancy: "73.1",
    elevation_in_meters: "450",
    continent: "South America",
    abbreviation: "VE",
    location: "South America",
    iso: "862",
    capital_city: "Caracas"
  },
  {
    country: "Vietnam",
    population: "95540800",
    sq_km_area: 331689,
    life_expectancy: "69.3",
    elevation_in_meters: "398",
    continent: "Asia",
    abbreviation: "VN",
    location: "Southeast Asia",
    iso: "704",
    capital_city: "Hanoi"
  },
  {
    country: "Virgin Islands, British",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "VG",
    location: null,
    iso: null,
    capital_city: "Road Town"
  },
  {
    country: "Virgin Islands, U.S.",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "North America",
    abbreviation: "VI",
    location: null,
    iso: null,
    capital_city: "Charlotte Amalie"
  },
  {
    country: "Wales",
    population: null,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Europe",
    location: null,
    iso: null,
    capital_city: "Cardiff"
  },
  {
    country: "Wallis and Futuna",
    population: "11773",
    sq_km_area: 200,
    life_expectancy: null,
    elevation_in_meters: null,
    continent: "Oceania",
    abbreviation: "WF",
    location: "Polynesia",
    iso: "876",
    capital_city: "Mata-Utu"
  },
  {
    country: "Western Sahara",
    population: "552628",
    sq_km_area: 266000,
    life_expectancy: "49.8",
    elevation_in_meters: "256",
    continent: "Africa",
    abbreviation: "EH",
    location: "Northern Africa",
    iso: "732",
    capital_city: "El-Aai"
  },
  {
    country: "Yemen",
    population: "28250420",
    sq_km_area: 527968,
    life_expectancy: "59.8",
    elevation_in_meters: "999",
    continent: "Asia",
    abbreviation: "YE",
    location: "Middle East",
    iso: "887",
    capital_city: "Sanaa"
  },
  {
    country: "Yugoslavia",
    population: "10640000",
    sq_km_area: 102173,
    life_expectancy: "72.4",
    elevation_in_meters: null,
    continent: "Europe",
    abbreviation: "YU",
    location: "Southern Europe",
    iso: null,
    capital_city: "Beograd"
  },
  {
    country: "Zambia",
    population: "17094130",
    sq_km_area: 752618,
    life_expectancy: "37.2",
    elevation_in_meters: "1,138",
    continent: "Africa",
    abbreviation: "ZM",
    location: "Eastern Africa",
    iso: "894",
    capital_city: "Lusaka"
  },
  {
    country: "Zimbabwe",
    population: "16529904",
    sq_km_area: 390757,
    life_expectancy: "37.8",
    elevation_in_meters: "961",
    continent: "Africa",
    abbreviation: "ZW",
    location: "Eastern Africa",
    iso: "716",
    capital_city: "Harare"
  }
]